CREATE TABLE patients(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    date_of_birth DATE
);

CREATE TABLE medical_histories(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admitted_at TIMESTAMP,
    patient_id INT,
    status VARCHAR,
    CONSTRAINT fk_patients FOREIGN KEY (patient_id) REFERENCES patients(id)
);

CREATE INDEX idx_medical_histories_patient ON medical_histories(patient_id);

CREATE TABLE invoices(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_amount DECIMAL,
    generated_at TIMESTAMP,
    payed_at TIMESTAMP,
    medical_history__id INT UNIQUE,
    CONSTRAINT fk_medical_histories FOREIGN KEY (medical_history__id) REFERENCES medical_histories(id)
);

CREATE TABLE treatments(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR,
    name VARCHAR
);

CREATE TABLE invoice_items(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_price DECIMAL,
    quantity INT,
    total_price DECIMAL,
    invoice_id INT,
    treatment_id INT,
    CONSTRAINT fk_invoices FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    CONSTRAINT fk_treatments FOREIGN KEY (treatment_id) REFERENCES treatments(id)
);

CREATE INDEX idx_invoice_items_invoice ON invoice_items(invoice_id);
CREATE INDEX idx_invoice_items__treatment ON invoice_items(treatment_id);

CREATE TABLE medical_history_items(
    medical_history__id INT,
    treatment_id INT,
    CONSTRAINT fk_medical_histories_items FOREIGN KEY (medical_history__id) REFERENCES medical_histories(id),
    CONSTRAINT fk_treatments_items FOREIGN KEY (treatment_id) REFERENCES treatments(id)
);

CREATE INDEX idx_medical_history ON medical_history_items(medical_history__id);
CREATE INDEX idx_treatment ON medical_history_items(treatment_id);