/* Database schema to keep the structure of entire database. */

CREATE TABLE owners(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(60) NOT NULL,
    age SMALLINT NOT NULL
);

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    date_of_birth DATE NOT NULL,
    escape_attempts SMALLINT NOT NULL,
    neutered BOOLEAN NOT NULL,
    weight_kg FLOAT NOT NULL,
    species_id INT NOT NULL,
    owner_id INT,
    CONSTRAINT fk_species
      FOREIGN KEY(species_id) 
	  REFERENCES species(id)
	  ON DELETE CASCADE,
    CONSTRAINT fk_owner
      FOREIGN KEY(owner_id) 
	  REFERENCES owners(id)
	  ON DELETE SET NULL
);